version : '3'

tasks:
  run:
    cmds:
      - go build -o bin/app cmd/corveyql/main.go
      - ./bin/app
  proto:
    cmds:
      - protoc -I ./internal/proto --go_out ./internal/proto --go_opt paths=source_relative --go-grpc_out ./internal/proto --go-grpc_opt paths=source_relative --grpc-gateway_out ./internal/proto --grpc-gateway_opt paths=source_relative --openapiv2_out ./internal/proto --openapiv2_opt use_go_templates=true internal/proto/main.proto

